@url = http://localhost:8000
### POST user register
POST {{url}}/api/register
Accept: application/json
Content-Type: application/json

{
    "name" : "Koxme",
    "email" : "Koxme123@gmail.com",
    "password" : "pasahitza",
    "password_confirmation": "pasahitza",
    "teacher" : 0
}

### POST user register
POST {{url}}/api/register
Accept: application/json
Content-Type: application/json

{
    "name" : "Oihan",
    "email" : "Oihan@gmail.com",
    "password" : "pasahitza123",
    "password_confirmation": "pasahitza123",
    "teacher" : 1

}


### POST user login ikaslea
POST {{url}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email" : "Koxme123@gmail.com",
    "password" : "pasahitza"
}

### POST user login irakaslea
POST {{url}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email" : "Oihan@gmail.com",
    "password" : "pasahitza123"
}

### POST user logout
POST {{url}}/api/logout
Authorization: Bearer 9|nCybrfozjXYuS2d9sqQ5SJCHSOhsctvRsc0XcYaO90767b32
Accept: application/json

### GET moduluak index
GET {{url}}/api/moduluak

### POST moduluak store
POST {{url}}/api/moduluak
Accept: application/json
Content-Type: application/json

{
    "izena" : "Gaztelera",
    "gela" : "2003-01-01"
}

### PUT moduluak update
PUT {{url}}/api/moduluak/1
Accept: application/json
Content-Type: application/json

{
    "izena" : "Ingelesa",
    "gela" : "2025-01-01"
}

### DELETE moduluak delete
DELETE  {{url}}/api/moduluak/2
Accept: application/json
Content-Type: application/json

### GET ikasleak index
GET {{url}}/api/ikasleak
Authorization: Bearer 7|vusj8EelhluXvPhcxe6I86QA3Ik6sM5pFcAmSk8N2cb9c0c1

### POST user moduluan erregistratu
POST {{url}}/api/ikaslemoduluak
Accept: application/json
Content-Type: application/json
Authorization: Bearer 10|QF9Z4MBks6zNZROOwujlnXGmg2Ofgbvpes9YFyPk491d7c72

{
    "modulua_id": 1
}